import '@mantine/core/styles.css';

import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import '@mantine/core/styles.css';



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Blog',
  description: 'Generated by Raymond Njagala',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <head>
        <ColorSchemeScript />
      </head>
       
      <body className={inter.className}>
        {/* <MantineProvider>{children}</MantineProvider> */}
        

        <Navbar/>
        
        <h1>hello</h1>
        {children}</body>
    </html>
  )
}
